name: Python Application Workflow
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          DISCORD_BOT_TOKEN: '${{ secrets.DISCORD_BOT_TOKEN }}'
        run: >
          echo "Running application with Gemini API key and Discord Bot
          token..."

          python Dicord boy\main.py
